version: '3.7'

services:
    app:
        build:
            context: .
        ports:
            - '80:80'
        volumes:
            - ./app:/app
        command: sh -c 'python3 manage.py runserver 0.0.0.0:80'
        #environment:
        env_file:
            #- DEBUG=1
            - ./.env.prod