# Generated by Django 3.0.9 on 2020-08-07 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(blank=True, max_length=300, verbose_name='Activo')),
                ('grs', models.CharField(max_length=25, null=True, verbose_name='Gramage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Laboratorio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('total_qty', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cantidad total de pzas')),
                ('med_function', models.TextField(blank=True, max_length=100, null=True, verbose_name='Función')),
                ('indications', models.TextField(blank=True, max_length=100, null=True, verbose_name='Indicaciones')),
                ('contraindications', models.TextField(blank=True, max_length=100, null=True, verbose_name='Contraindicaciones')),
                ('cad', models.DateField(verbose_name='Caducidad')),
                ('med_qty', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Unidades disponibles por caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('active', models.ManyToManyField(to='medicine.Active', verbose_name='Activo')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medicine.MedCode', verbose_name='Codigo único')),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medicine.Laboratory', verbose_name='Laboratorio')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medicine.Lot', verbose_name='Lote')),
                ('med_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medicine.MedType', verbose_name='Tipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(max_length=2000, verbose_name='Descripciòn')),
                ('qty', models.CharField(max_length=1000, verbose_name='Cantidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
