# Generated by Django 3.0.9 on 2020-08-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='formule',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='function',
            field=models.TextField(max_length=100),
        ),
    ]
