# Generated by Django 3.0.9 on 2020-08-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20200804_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='contraindications',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='indications',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
