# Generated by Django 3.0.9 on 2020-08-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20200804_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='active',
        ),
        migrations.AddField(
            model_name='medicine',
            name='med_type',
            field=models.CharField(choices=[('Pastilla', 'phill'), ('Solucion', 'solution'), ('Inyeccion', 'injection'), ('En Polvo', 'powdered')], default='Pastilla', max_length=50, verbose_name='Tipo de medicamento'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='cad',
            field=models.DateField(verbose_name='Caducidad'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='contraindications',
            field=models.TextField(max_length=100, verbose_name='Contraindicaciones'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='disp_qty',
            field=models.CharField(max_length=1000, verbose_name='Cantida Disponible'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='formule',
            field=models.TextField(max_length=100, verbose_name='Formula'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='function',
            field=models.TextField(max_length=100, verbose_name='Funciòn'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='indications',
            field=models.TextField(max_length=100, null=True, verbose_name='Indicaciones'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='laboratory',
            field=models.CharField(max_length=100, verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='total_qty',
            field=models.CharField(max_length=1000, null=True, verbose_name='Cantidad total de pzas'),
        ),
    ]
