# Generated by Django 3.0.9 on 2020-08-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='active',
            field=models.ManyToManyField(to='medicine.Active'),
        ),
    ]
