# Generated by Django 3.0.9 on 2020-08-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_medicine_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='active',
            field=models.ManyToManyField(to='medicine.Active', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='contraindications',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Contraindicaciones'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='disp_qty',
            field=models.CharField(max_length=1000, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='function',
            field=models.TextField(max_length=100, verbose_name='Función'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='med_type',
            field=models.CharField(choices=[('phill', 'Pastilla'), ('solution', 'Solucion'), ('injection', 'Inyeccion'), ('powdered', 'En Polvo')], default='Pastilla', max_length=50, verbose_name='Tipo de medicamento'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='total_qty',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cantidad total de pzas'),
        ),
    ]
