# Generated by Django 3.0.9 on 2020-08-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_auto_20200804_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='name',
        ),
    ]
