# Generated by Django 3.0.9 on 2020-08-04 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_auto_20200804_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medicine.Name', verbose_name='Nombre'),
        ),
    ]
